language: ruby
rvm:
  - 2.3
sudo: required
services:
  - docker

env:
    matrix:
        - SCRIPT=docker DIST=stretch
        - SCRIPT=php DIST=wheezy PHP_VERSION=5.4 PHP_SAPI=apache2
        - SCRIPT=php DIST=wheezy PHP_VERSION=5.4 PHP_SAPI=fpm
        - SCRIPT=php DIST=jessie PHP_VERSION=5.6 PHP_SAPI=apache2
        - SCRIPT=php DIST=jessie PHP_VERSION=5.6 PHP_SAPI=fpm
        - SCRIPT=php DIST=stretch PHP_VERSION=7.0 PHP_SAPI=apache2
        - SCRIPT=php DIST=stretch PHP_VERSION=7.0 PHP_SAPI=fpm
        - SCRIPT=ssh DIST=stretch
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=6 TOMCAT_VERSION=6
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=6 TOMCAT_VERSION=6 ONBUILD=yes
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=6 TOMCAT_VERSION=7
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=6 TOMCAT_VERSION=7 ONBUILD=yes
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=7 TOMCAT_VERSION=6
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=7 TOMCAT_VERSION=6 ONBUILD=yes
        - SCRIPT=tomcat DIST=jessie JAVA_VERSION=7 TOMCAT_VERSION=7
        - SCRIPT=tomcat DIST=jessie JAVA_VERSION=7 TOMCAT_VERSION=7 ONBUILD=yes
        - SCRIPT=tomcat DIST=jessie JAVA_VERSION=7 TOMCAT_VERSION=8
        - SCRIPT=tomcat DIST=jessie JAVA_VERSION=7 TOMCAT_VERSION=8 ONBUILD=yes
        - SCRIPT=tomcat DIST=stretch JAVA_VERSION=8 TOMCAT_VERSION=8.5
        - SCRIPT=tomcat DIST=stretch JAVA_VERSION=8 TOMCAT_VERSION=8.5 ONBUILD=yes

script:
    - ./generate.sh $SCRIPT
    - ./build.sh $SCRIPT
    - ./test.sh $SCRIPT
after_success:
  - if [ "$TRAVIS_REPO_SLUG" = nantesmetropole/docker-paas -a "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" = false ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    ./push.sh $SCRIPT;
    fi
