language: generic
sudo: required
services:
  - docker

env:
    matrix:
        - SCRIPT=docker DIST=stretch
        - SCRIPT=docker-registry DIST=stretch
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=6 TOMCAT_VERSION=6
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=6 TOMCAT_VERSION=6 ONBUILD=yes
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=6 TOMCAT_VERSION=7
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=6 TOMCAT_VERSION=7 ONBUILD=yes
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=7 TOMCAT_VERSION=6
        - SCRIPT=tomcat DIST=wheezy JAVA_VERSION=7 TOMCAT_VERSION=6 ONBUILD=yes
        - SCRIPT=tomcat DIST=jessie JAVA_VERSION=7 TOMCAT_VERSION=7
        - SCRIPT=tomcat DIST=jessie JAVA_VERSION=7 TOMCAT_VERSION=7 ONBUILD=yes
        - SCRIPT=tomcat DIST=jessie JAVA_VERSION=7 TOMCAT_VERSION=8
        - SCRIPT=tomcat DIST=jessie JAVA_VERSION=7 TOMCAT_VERSION=8 ONBUILD=yes
        - SCRIPT=tomcat DIST=stretch JAVA_VERSION=8 TOMCAT_VERSION=8.5
        - SCRIPT=tomcat DIST=stretch JAVA_VERSION=8 TOMCAT_VERSION=8.5 ONBUILD=yes

script:
    - ./generate.sh $SCRIPT
    - ./build.sh $SCRIPT
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    ./push.sh $SCRIPT;
    fi
